language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - make requirements
  - pip install -r requirements-test.txt
  - pip install coveralls
# command to run tests
script:
  - flake8 tests
  - nosetests --with-coverage -d --cover-package=dirty_models

after_success:
  - coveralls --rcfile=.coveragerc

cache: pip
sudo: false
